### ISSUE TITLE
change in lmm.findH2_2K?

### ISSUE THREAD

**Issue by espride** [MicrosoftGenomics/FaST-LMM#35]
Hello,

I have been working with a script written by a previous graduate student that uses the lmm.findH2_2K function.  This has worked for several years using the fastlmm-0.2.21-py2.7.  However, due to a recent change in python environment, I have had to re-install my python packages using conda (conda install fastlmm) which installed fastlmm-0.2.3.-py27_1.   However, once I run the following code, I receive the following error:

I have run old data that has previously worked but is no also giving the same error.  Do you by chance know if there was a change in the syntax or required input?  Any help would be greatly appreciated:
code:
>W=G1_standardized_val.copy()  #where W is an array (236,3)
>UGup,UUGUp=lmm.rotate(W)
>i_up=np.zeros((W.shape[1]),dtype=np.bool) #where i_up is a numby array of 3 rows with the value False
>i_G1=np.ones((W.shape[1]),dtype=np.bool) #where i_G1 is a numpy array of 3 rows with the value True
> result=lmm.findH2_2K(nGridH2=10, minH2=0.0, maxH2=0.999,  i_up=iup, i_G1=i_G1, UW=UGup, UUW=UUGup)

Error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mccuem/norto253/.conda/envs/EMS_GWAS/lib/python2.7/site-packages/fastlmm/inference/lmm_cov.py", line 383, in findH2_2K
    min = minimize1D(f=f, nGrid=nGridH2, minval=minH2, maxval=maxH2)
  File "/home/mccuem/norto253/.conda/envs/EMS_GWAS/lib/python2.7/site-packages/fastlmm/util/mingrid.py", line 33, in minimize1D
    [evalgrid,resultgrid] = evalgrid1D(f, evalgrid = evalgrid, nGrid=nGrid, minval=minval, maxval = maxval  )
  File "/home/mccuem/norto253/.conda/envs/EMS_GWAS/lib/python2.7/site-packages/fastlmm/util/mingrid.py", line 92, in evalgrid1D
    fevalgrid = f(evalgrid[i])
  File "/home/mccuem/norto253/.conda/envs/EMS_GWAS/lib/python2.7/site-packages/fastlmm/inference/lmm_cov.py", line 379, in f
    res = self.innerLoop_2K(h2=x, i_up=i_up, i_G1=i_G1, UW=UW, UUW=UUW, nGridA2=nGridA2, minA2=minA2, maxA2=maxA2, **kwargs)
  File "/home/mccuem/norto253/.conda/envs/EMS_GWAS/lib/python2.7/site-packages/fastlmm/inference/lmm_cov.py", line 290, in innerLoop_2K
    return self.findA2_2K(nGridA2=nGridA2, minA2=minA2, maxA2=maxA2, i_up=i_up, i_G1=i_G1, UW=UW, UUW=UUW, h2=h2, **kwargs)
  File "/home/mccuem/norto253/.conda/envs/EMS_GWAS/lib/python2.7/site-packages/fastlmm/inference/lmm_cov.py", line 338, in findA2_2K
    min = minimize1D(f=f, nGrid=nGridA2, minval=minA2, maxval=maxA2,verbose=False)
  File "/home/mccuem/norto253/.conda/envs/EMS_GWAS/lib/python2.7/site-packages/fastlmm/util/mingrid.py", line 33, in minimize1D
    [evalgrid,resultgrid] = evalgrid1D(f, evalgrid = evalgrid, nGrid=nGrid, minval=minval, maxval = maxval  )
  File "/home/mccuem/norto253/.conda/envs/EMS_GWAS/lib/python2.7/site-packages/fastlmm/util/mingrid.py", line 93, in evalgrid1D
    assert SP.isreal(fevalgrid).all(),"function returned imaginary value"
AttributeError: 'bool' object has no attribute 'all'

Any help would be greatly appreciated.  Thank you.

**Comment by espride** [comment]
Yes, I think that worked!  Thank you!

**Comment by CarlKCarlK** [comment]
Fixed in GitHub and PyPi
