### ISSUE TITLE
raise AssertionError(msg)

### ISSUE THREAD

**Issue by mycecilia** [MicrosoftGenomics/FaST-LMM#4]
I got the error massage as following:

running feature selection conditioned on background kernel
[1, 2, 5, 11, 25, 57, 128]

Traceback (most recent call last):
  File "snipeallselect.py", line 54, in <module>
    best_k, feat_idx, best_mix, best_delta = select.run_select(G0.val, G0.val, y)
  File "/home/GLBRCORG/schen52/.python/lib/python2.7/site-packages/fastlmm-0.2.14-py2.7-linux-x86_64.egg/fastlmm/feature_selection/feature_selection_two_kernel.py", line 124, in run_select
    np.testing.assert_almost_equal(sum(np.diag(K_bg_full)), G_bg.shape[0])
  File "/opt/bifxapps/python/lib/python2.7/site-packages/numpy-1.7.1-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 468, in assert_almost_equal
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 7 decimals
 ACTUAL: 513.99999947000538
 DESIRED: 514

I'm running the software on a remote Linux machine. 

I have 514 individuals for testing, How could the number ever be non-integer? Thank you.

**Comment by CarlKCarlK** [comment]
Thanks for the bug report. I think it's just a problem with numerical precision.
Can you try editing your file:
"/home/GLBRCORG/schen52/.python/lib/python2.7/site-packages/fastlmm-0.2.14-py2.7-linux-x86_64.egg/fastlmm/feature_selection/feature_selection_two_kernel.py
and changing line 124 so that it reads:
np.testing.assert_almost_equal(sum(np.diag(K_bg_full)), G_bg.shape[0], decimal=6)

**Comment by mycecilia** [comment]
It's working well now. Thank you.
